package com.javapuebla.bd.domain;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.id
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.firstName
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.lastName
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.email
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.status
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.id
     *
     * @return the value of Customer.id
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.id
     *
     * @param id the value for Customer.id
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.firstName
     *
     * @return the value of Customer.firstName
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.firstName
     *
     * @param firstName the value for Customer.firstName
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.lastName
     *
     * @return the value of Customer.lastName
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.lastName
     *
     * @param lastName the value for Customer.lastName
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.email
     *
     * @return the value of Customer.email
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.email
     *
     * @param email the value for Customer.email
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.status
     *
     * @return the value of Customer.status
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.status
     *
     * @param status the value for Customer.status
     *
     * @mbggenerated Tue Dec 09 11:44:07 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}